# See default settings https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/bundle/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'

# Limit lines to 120 characters.
LineLength:
  Enabled: false

# Avoid methods longer than 50 lines of code
MethodLength:
  Enabled: true
  Max: 50

# Add underscores to large numeric literals to improve their readability.
NumericLiterals:
  Enabled: false

# Prefer ' strings when you don't need string interpolation or special symbols.
StringLiterals:
  Enabled: false

# Document classes and non-namespace modules.
Documentation:
  Enabled: false

# Assignment Branch Condition size for create is too high.
AbcSize:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

AlignHash:
  EnforcedColonStyle: key

RaiseArgs:
  EnforcedStyle: compact

ClassAndModuleChildren:
  EnforcedStyle: compact

CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 10
