default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  charset: utf8mb4
  encoding: utf8mb4

development:
  <<: *default
  database: nuko_development

test:
  <<: *default
  database: nuko_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: nuko_production
  username: nuko
  password: <%= ENV['NUKO_DATABASE_PASSWORD'] %>
