default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: nuko_development

test:
  <<: *default
  database: nuko_test

production:
  <<: *default
  database: nuko_production
  username: nuko
  password: <%= ENV['NUKO_DATABASE_PASSWORD'] %>
