default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: <%= ENV['DATABASE_SOCKET'] || '/tmp/mysql.sock' %>
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci

development:
  <<: *default
  database: nuko_development

test:
  <<: *default
  database: nuko_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: nuko_production
  username: nuko
  password: <%= ENV['NUKO_DATABASE_PASSWORD'] %>
